// <auto-generated />
using System;
using EcMnt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EcMnt.Migrations
{
    [DbContext(typeof(EcContext))]
    [Migration("20181117063305_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EcMnt.Models.Accounts.Account", b =>
                {
                    b.Property<string>("idAccount")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("IdMerchant")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("avt_path")
                        .IsRequired();

                    b.Property<string>("idCustomer")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("passwd")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("rankVip");

                    b.Property<int>("rate");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("idAccount");

                    b.HasIndex("IdMerchant");

                    b.HasIndex("idCustomer");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EcMnt.Models.Accounts.Address", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addressid");

                    b.Property<string>("City_Provine")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("District_town")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("add_Info")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("idAccount")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("subDistrict")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.HasIndex("Addressid");

                    b.HasIndex("idAccount");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("EcMnt.Models.Accounts.Email", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("Addressid");

                    b.Property<string>("IdAccount")
                        .HasMaxLength(10);

                    b.Property<string>("email");

                    b.HasKey("id");

                    b.HasIndex("Addressid");

                    b.HasIndex("IdAccount");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("EcMnt.Models.Advertisements.Advertisement", b =>
                {
                    b.Property<string>("idAdvertisement")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<int?>("PositionidPosition");

                    b.Property<DateTime>("creat_date");

                    b.Property<int>("expire");

                    b.Property<string>("idAccount")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("position");

                    b.HasKey("idAdvertisement");

                    b.HasIndex("PositionidPosition");

                    b.HasIndex("idAccount");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("EcMnt.Models.Advertisements.Position", b =>
                {
                    b.Property<int>("idPosition")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("height");

                    b.Property<float>("width");

                    b.HasKey("idPosition");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("EcMnt.Models.Bills.BillState", b =>
                {
                    b.Property<int>("idState")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("idState");

                    b.ToTable("BillStates");
                });

            modelBuilder.Entity("EcMnt.Models.Bills.ItemOrderList", b =>
                {
                    b.Property<string>("idList")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<int>("avgRate");

                    b.Property<int>("count");

                    b.Property<string>("idOrder")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("idProduct")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("idList");

                    b.HasIndex("idOrder");

                    b.HasIndex("idProduct");

                    b.ToTable("ItemOrderLists");
                });

            modelBuilder.Entity("EcMnt.Models.Bills.Order", b =>
                {
                    b.Property<string>("idOrder")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("AccountidAccount");

                    b.Property<string>("Addressid");

                    b.Property<int?>("BillStateidState");

                    b.Property<string>("IdSaleAcc")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("creat_date");

                    b.Property<string>("idBuyAcc")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("idStt");

                    b.Property<double>("total");

                    b.HasKey("idOrder");

                    b.HasIndex("AccountidAccount");

                    b.HasIndex("Addressid");

                    b.HasIndex("BillStateidState");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcMnt.Models.Bills.Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cmt")
                        .IsRequired();

                    b.Property<string>("ItemOrderListidList");

                    b.Property<int>("idItemOrderList");

                    b.Property<int>("rateValue");

                    b.HasKey("id");

                    b.HasIndex("ItemOrderListidList");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("EcMnt.Models.Extensions.historySearch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountidAccount");

                    b.Property<string>("idAcc")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("keyword");

                    b.HasKey("id");

                    b.HasIndex("AccountidAccount");

                    b.ToTable("HistorySearches");
                });

            modelBuilder.Entity("EcMnt.Models.OnlinePost.Post", b =>
                {
                    b.Property<string>("idPost")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<DateTime>("create_date");

                    b.Property<int>("curRank");

                    b.Property<string>("idAcc")
                        .IsRequired();

                    b.HasKey("idPost");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EcMnt.Models.OnlinePost.Show", b =>
                {
                    b.Property<string>("idShow")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("Intro");

                    b.Property<string>("idPost")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("idProduct")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("idShow");

                    b.HasIndex("idPost");

                    b.HasIndex("idProduct");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("EcMnt.Models.Product", b =>
                {
                    b.Property<string>("idProduct")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("brand")
                        .HasMaxLength(20);

                    b.Property<string>("code")
                        .HasMaxLength(100);

                    b.Property<string>("description")
                        .HasMaxLength(100);

                    b.Property<string>("idCategory")
                        .IsRequired();

                    b.Property<string>("nameProduct");

                    b.HasKey("idProduct");

                    b.HasIndex("idCategory");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EcMnt.Models.Products.Category", b =>
                {
                    b.Property<string>("idCategory")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("link_imageCategory");

                    b.Property<string>("nameCategory")
                        .IsRequired();

                    b.HasKey("idCategory");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EcMnt.Models.Products.ImageProduct", b =>
                {
                    b.Property<string>("idImage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<int>("idproductDetail");

                    b.Property<string>("link_Image")
                        .HasMaxLength(40);

                    b.Property<string>("productDetailidproductDetail");

                    b.HasKey("idImage");

                    b.HasIndex("productDetailidproductDetail");

                    b.ToTable("ImageProducts");
                });

            modelBuilder.Entity("EcMnt.Models.Products.productDetail", b =>
                {
                    b.Property<string>("idproductDetail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("AccountidAccount");

                    b.Property<string>("IdAcc")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("IdRepository")
                        .HasMaxLength(10);

                    b.Property<int>("count");

                    b.Property<DateTime>("creat_date");

                    b.Property<float>("fee");

                    b.Property<string>("idProduct")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<double>("price");

                    b.HasKey("idproductDetail");

                    b.HasIndex("AccountidAccount");

                    b.HasIndex("IdRepository");

                    b.HasIndex("idProduct")
                        .IsUnique();

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.ExportForm", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<DateTime>("creat_date");

                    b.Property<string>("idRepository")
                        .IsRequired();

                    b.Property<double>("total");

                    b.HasKey("id");

                    b.HasIndex("idRepository");

                    b.ToTable("ExportForms");
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.ImportForm", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<DateTime>("creat_date");

                    b.Property<string>("idRepository")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<double>("total");

                    b.HasKey("id");

                    b.HasIndex("idRepository");

                    b.ToTable("ImportForms");
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.ItemEplist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExportFormid");

                    b.Property<string>("ProductidProduct");

                    b.Property<int>("count");

                    b.Property<int>("idEpform");

                    b.Property<int>("idProduct");

                    b.HasKey("id");

                    b.HasIndex("ExportFormid");

                    b.HasIndex("ProductidProduct");

                    b.ToTable("ItemEplists");
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.ItemIplist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImportFormid");

                    b.Property<int>("count");

                    b.Property<string>("idIpForm")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("idProduct")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("id");

                    b.HasIndex("ImportFormid");

                    b.HasIndex("idProduct");

                    b.ToTable("ItemIplists");
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.Repository", b =>
                {
                    b.Property<string>("idRepository")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("Stt");

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("idRepository");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("EcMnt.Models.Users.Customer", b =>
                {
                    b.Property<string>("idCustomer")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("fstname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("lstname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("phone")
                        .IsRequired();

                    b.HasKey("idCustomer");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EcMnt.Models.Users.Link_ImgStore", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("CustomeridCustomer");

                    b.Property<string>("idMerchant");

                    b.Property<string>("path")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("CustomeridCustomer");

                    b.HasIndex("idMerchant");

                    b.ToTable("Link_ImgStores");
                });

            modelBuilder.Entity("EcMnt.Models.Users.Merchant", b =>
                {
                    b.Property<string>("idMerchant")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("fstname")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("lstname")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("phone")
                        .IsRequired();

                    b.Property<string>("storename")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("website");

                    b.HasKey("idMerchant");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("EcMnt.Models.Accounts.Account", b =>
                {
                    b.HasOne("EcMnt.Models.Users.Merchant", "Merchant")
                        .WithMany("Accounts")
                        .HasForeignKey("IdMerchant")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EcMnt.Models.Users.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("idCustomer")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Accounts.Address", b =>
                {
                    b.HasOne("EcMnt.Models.Accounts.Address")
                        .WithMany("Addresses")
                        .HasForeignKey("Addressid");

                    b.HasOne("EcMnt.Models.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("idAccount")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Accounts.Email", b =>
                {
                    b.HasOne("EcMnt.Models.Accounts.Address")
                        .WithMany("Emails")
                        .HasForeignKey("Addressid");

                    b.HasOne("EcMnt.Models.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("IdAccount");
                });

            modelBuilder.Entity("EcMnt.Models.Advertisements.Advertisement", b =>
                {
                    b.HasOne("EcMnt.Models.Advertisements.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionidPosition");

                    b.HasOne("EcMnt.Models.Accounts.Account", "Account")
                        .WithMany("Advertisements")
                        .HasForeignKey("idAccount")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Bills.ItemOrderList", b =>
                {
                    b.HasOne("EcMnt.Models.Bills.Order", "Order")
                        .WithMany()
                        .HasForeignKey("idOrder")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EcMnt.Models.Product", "Product")
                        .WithMany("ItemOrderLists")
                        .HasForeignKey("idProduct")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Bills.Order", b =>
                {
                    b.HasOne("EcMnt.Models.Accounts.Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountidAccount");

                    b.HasOne("EcMnt.Models.Accounts.Address")
                        .WithMany("Orders")
                        .HasForeignKey("Addressid");

                    b.HasOne("EcMnt.Models.Bills.BillState", "BillState")
                        .WithMany("Orders")
                        .HasForeignKey("BillStateidState");
                });

            modelBuilder.Entity("EcMnt.Models.Bills.Rating", b =>
                {
                    b.HasOne("EcMnt.Models.Bills.ItemOrderList", "ItemOrderList")
                        .WithMany("Ratings")
                        .HasForeignKey("ItemOrderListidList");
                });

            modelBuilder.Entity("EcMnt.Models.Extensions.historySearch", b =>
                {
                    b.HasOne("EcMnt.Models.Accounts.Account", "Account")
                        .WithMany("HistorySearches")
                        .HasForeignKey("AccountidAccount");
                });

            modelBuilder.Entity("EcMnt.Models.OnlinePost.Show", b =>
                {
                    b.HasOne("EcMnt.Models.OnlinePost.Post", "Post")
                        .WithMany("Shows")
                        .HasForeignKey("idPost")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EcMnt.Models.Product", "Products")
                        .WithMany("Shows")
                        .HasForeignKey("idProduct")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Product", b =>
                {
                    b.HasOne("EcMnt.Models.Products.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("idCategory")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Products.ImageProduct", b =>
                {
                    b.HasOne("EcMnt.Models.Products.productDetail", "productDetail")
                        .WithMany("ImageProducts")
                        .HasForeignKey("productDetailidproductDetail");
                });

            modelBuilder.Entity("EcMnt.Models.Products.productDetail", b =>
                {
                    b.HasOne("EcMnt.Models.Accounts.Account", "Account")
                        .WithMany("ProductDetails")
                        .HasForeignKey("AccountidAccount");

                    b.HasOne("EcMnt.Models.Repositories.Repository", "Repository")
                        .WithMany("ProductDetails")
                        .HasForeignKey("IdRepository");

                    b.HasOne("EcMnt.Models.Product", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("EcMnt.Models.Products.productDetail", "idProduct")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.ExportForm", b =>
                {
                    b.HasOne("EcMnt.Models.Repositories.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("idRepository")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.ImportForm", b =>
                {
                    b.HasOne("EcMnt.Models.Repositories.Repository", "Repository")
                        .WithMany("ImportForms")
                        .HasForeignKey("idRepository")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.ItemEplist", b =>
                {
                    b.HasOne("EcMnt.Models.Repositories.ExportForm", "ExportForm")
                        .WithMany("ItemExlists")
                        .HasForeignKey("ExportFormid");

                    b.HasOne("EcMnt.Models.Product", "Product")
                        .WithMany("ItemEpLists")
                        .HasForeignKey("ProductidProduct");
                });

            modelBuilder.Entity("EcMnt.Models.Repositories.ItemIplist", b =>
                {
                    b.HasOne("EcMnt.Models.Repositories.ImportForm", "ImportForm")
                        .WithMany("ItemIplists")
                        .HasForeignKey("ImportFormid");

                    b.HasOne("EcMnt.Models.Product", "Product")
                        .WithMany("ItemIpLists")
                        .HasForeignKey("idProduct")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EcMnt.Models.Users.Link_ImgStore", b =>
                {
                    b.HasOne("EcMnt.Models.Users.Customer")
                        .WithMany("Link_ImgStores")
                        .HasForeignKey("CustomeridCustomer");

                    b.HasOne("EcMnt.Models.Users.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("idMerchant");
                });
#pragma warning restore 612, 618
        }
    }
}
